@startuml
left to right direction
:발송회사:
:화물기사: 
:수취회사:
package TISSystem {
	usecase "배송기사등록"
	usecase "화물등록"
	usecase "수취회사등록"
	usecase "기사위치확인"
	usecase "알림"
	usecase "지연정보제공"
}

발송회사 --> 배송기사등록
발송회사 --> 화물등록
발송회사 --> 수취회사등록
발송회사 <-------- 기사위치확인
발송회사 <-- 알림
지연정보제공 --> 발송회사

기사위치확인 --> 화물기사
알림 --> 화물기사
지연정보제공 <--  화물기사



수취회사 <--- 기사위치확인
지연정보제공 ---> 수취회사

@enduml